In [235]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [236]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1i0PiCCl9dXhxMDuR47a2TOQWrsa99m650wq_hHbawHY/export?format=csv")

In [237]:
df.shape

(14775, 9)

In [238]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14775 entries, 0 to 14774
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   listing_id  14740 non-null  float64
 1   title       14775 non-null  object
 2   price_text  14775 non-null  object
 3   price_pkr   14775 non-null  int64
 4   location    14775 non-null  object
 5   area_text   14775 non-null  object
 6   area_marla  14775 non-null  float64
 7   beds        13868 non-null  float64
 8   baths       13735 non-null  float64
dtypes: float64(4), int64(1), object(4)
memory usage: 1.0+ MB

In [239]:
df.isnull().sum()

listing_id      35
title            0
price_text       0
price_pkr        0
location         0
area_text        0
area_marla       0
beds           907
baths         1040
dtype: int64

In [240]:
df.describe()

         listing_id     price_pkr    area_marla          beds         baths
count  1.474000e+04  1.477500e+04  14775.000000  13868.000000  13735.000000
mean   5.410078e+07  9.304380e+07     15.953861      4.453057      4.555661
std    1.590959e+06  1.698869e+08     47.993253      1.983534      1.806038
min    1.745226e+07  8.000000e+04      0.900000      1.000000      1.000000
25%    5.411223e+07  2.500000e+07      5.000000      3.000000      3.000000
50%    5.460245e+07  4.450000e+07      8.000000      5.000000      5.000000
75%    5.477557e+07  9.250000e+07     14.400000      6.000000      6.000000
max    5.487768e+07  4.000000e+09   1760.000000     11.000000     10.000000

In [241]:
df.head()

,listing_id,title,price_text,price_pkr,location,area_text,area_marla,beds,baths
0,54844773.0,House At Prime Location,5.5 Crore,55000000,"D-12/1, D-12",4 Marla,4.0,3.0,5.0
1,54852451.0,Luxury 3-Bedroom Apartment For Sale In Warda H...,5.15 Crore,51500000,"Warda Hamna Residencia, G-11 Markaz",8.7 Marla,8.7,3.0,3.0
2,52696760.0,One kanal Beautiful luxurious FULL FURNISHED H...,10.9 Crore,109000000,"DHA Defence Phase 2, DHA Defence",1 Kanal,20.0,5.0,6.0
3,54793832.0,1 Kanal Luxury House Most Beautiful Prime Loca...,11.9 Crore,119000000,"DHA Defence Phase 2, DHA Defence",1 Kanal,20.0,6.0,6.0
4,54798682.0,Investor Price 1 Kanal Elegant House For Sale ...,7.9 Crore,79000000,"DHA Defence Phase 3, DHA Defence",1 Kanal,20.0,5.0,6.0

In [242]:
df.isnull().sum()

listing_id      35
title            0
price_text       0
price_pkr        0
location         0
area_text        0
area_marla       0
beds           907
baths         1040
dtype: int64

In [243]:
df1 = df.drop(columns=["listing_id", "title", "price_text", "area_text"])

In [244]:
df1.isnull().sum()

price_pkr        0
location         0
area_marla       0
beds           907
baths         1040
dtype: int64

In [245]:
df2 = df1.dropna()

In [246]:
df2

,price_pkr,location,area_marla,beds,baths
0,55000000,"D-12/1, D-12",4.0,3.0,5.0
1,51500000,"Warda Hamna Residencia, G-11 Markaz",8.7,3.0,3.0
2,109000000,"DHA Defence Phase 2, DHA Defence",20.0,5.0,6.0
3,119000000,"DHA Defence Phase 2, DHA Defence",20.0,6.0,6.0
4,79000000,"DHA Defence Phase 3, DHA Defence",20.0,5.0,6.0
...,...,...,...,...,...
14770,7500000,"Taramrri, Islamabad",4.0,3.0,2.0
14771,15500000,"Faisal Hills - Block A, Faisal Hills",5.0,3.0,4.0
14772,17000000,"PHAF Officers Residencia, Kuri Road",4.4,3.0,2.0
14773,82500000,"Margalla Town Phase 2, Margalla Town",8.0,7.0,6.0
14774,42000000,"G-11, Islamabad",4.4,5.0,5.0

In [247]:
df2.duplicated().sum()

np.int64(2763)

In [248]:
df3 = df2.drop_duplicates()

In [249]:
display(df3.shape)
display(df3.duplicated().sum())
display(df3.isnull().sum())

(10733, 5)

np.int64(0)

price_pkr     0
location      0
area_marla    0
beds          0
baths         0
dtype: int64

In [250]:
df3.head()

   price_pkr                             location  area_marla  beds  baths
0   55000000                         D-12/1, D-12         4.0   3.0    5.0
1   51500000  Warda Hamna Residencia, G-11 Markaz         8.7   3.0    3.0
2  109000000     DHA Defence Phase 2, DHA Defence        20.0   5.0    6.0
3  119000000     DHA Defence Phase 2, DHA Defence        20.0   6.0    6.0
4   79000000     DHA Defence Phase 3, DHA Defence        20.0   5.0    6.0

In [251]:
df3["sqrt_ft"] = df["area_marla"] * 272.251
df3.head()

/tmp/ipykernel_6280/1015283828.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3["sqrt_ft"] = df["area_marla"] * 272.251

,price_pkr,location,area_marla,beds,baths,sqrt_ft
0,55000000,"D-12/1, D-12",4.0,3.0,5.0,1089.0040
1,51500000,"Warda Hamna Residencia, G-11 Markaz",8.7,3.0,3.0,2368.5837
2,109000000,"DHA Defence Phase 2, DHA Defence",20.0,5.0,6.0,5445.0200
3,119000000,"DHA Defence Phase 2, DHA Defence",20.0,6.0,6.0,5445.0200
4,79000000,"DHA Defence Phase 3, DHA Defence",20.0,5.0,6.0,5445.0200

In [252]:
df3["price_per_sqrt_ft"] = df3["price_pkr"] / df3["sqrt_ft"]
df3["price_per_marla"] = df3["price_pkr"] / df3["area_marla"]

/tmp/ipykernel_6280/1498609760.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3["price_per_sqrt_ft"] = df3["price_pkr"] / df3["sqrt_ft"]
/tmp/ipykernel_6280/1498609760.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3["price_per_marla"] = df3["price_pkr"] / df3["area_marla"]

In [253]:
df3.head()

,price_pkr,location,area_marla,beds,baths,sqrt_ft,price_per_sqrt_ft,price_per_marla
0,55000000,"D-12/1, D-12",4.0,3.0,5.0,1089.0040,50504.864996,1.375000e+07
1,51500000,"Warda Hamna Residencia, G-11 Markaz",8.7,3.0,3.0,2368.5837,21742.951284,5.919540e+06
2,109000000,"DHA Defence Phase 2, DHA Defence",20.0,5.0,6.0,5445.0200,20018.291944,5.450000e+06
3,119000000,"DHA Defence Phase 2, DHA Defence",20.0,6.0,6.0,5445.0200,21854.832489,5.950000e+06
4,79000000,"DHA Defence Phase 3, DHA Defence",20.0,5.0,6.0,5445.0200,14508.670308,3.950000e+06

In [254]:
df4 = df3.copy()

In [255]:
def correctLocationNames(location):
  return location.strip().split(", ")[0].split("/")[0]

In [256]:
df4["location"] = df4["location"].apply(correctLocationNames)
len(df.location.unique())

666

In [257]:
df4.head()

,price_pkr,location,area_marla,beds,baths,sqrt_ft,price_per_sqrt_ft,price_per_marla
0,55000000,D-12,4.0,3.0,5.0,1089.0040,50504.864996,1.375000e+07
1,51500000,Warda Hamna Residencia,8.7,3.0,3.0,2368.5837,21742.951284,5.919540e+06
2,109000000,DHA Defence Phase 2,20.0,5.0,6.0,5445.0200,20018.291944,5.450000e+06
3,119000000,DHA Defence Phase 2,20.0,6.0,6.0,5445.0200,21854.832489,5.950000e+06
4,79000000,DHA Defence Phase 3,20.0,5.0,6.0,5445.0200,14508.670308,3.950000e+06

In [258]:
locations_stats = df4.groupby("location")["location"].agg("count").sort_values(ascending=False)
locations_stats

location
DHA Defence Phase 2     451
G-13                    390
Bani Gala               356
B-17                    282
D-12                    273
                       ...
Aryan Enclave             1
The Palazzo               1
Askari Heights            1
Top City 1 - Block I      1
Tower 45                  1
Name: location, Length: 533, dtype: int64

In [259]:
locations_stats_less_10 = locations_stats[locations_stats < 10]
locations_stats_less_10

location
Ghauri Town                  9
Soan Garden - Block D        9
Thanda Pani                  9
Capital Heights              9
Naval Anchorage - Block F    9
                            ..
Aryan Enclave                1
The Palazzo                  1
Askari Heights               1
Top City 1 - Block I         1
Tower 45                     1
Name: location, Length: 347, dtype: int64

In [260]:
df4["location"] = df4["location"].apply(lambda x: "other" if x in locations_stats_less_10 else x )

In [261]:
len(df4["location"].unique())

187

In [262]:
df5 = df4.copy()

In [263]:
df5.head()

,price_pkr,location,area_marla,beds,baths,sqrt_ft,price_per_sqrt_ft,price_per_marla
0,55000000,D-12,4.0,3.0,5.0,1089.0040,50504.864996,1.375000e+07
1,51500000,Warda Hamna Residencia,8.7,3.0,3.0,2368.5837,21742.951284,5.919540e+06
2,109000000,DHA Defence Phase 2,20.0,5.0,6.0,5445.0200,20018.291944,5.450000e+06
3,119000000,DHA Defence Phase 2,20.0,6.0,6.0,5445.0200,21854.832489,5.950000e+06
4,79000000,DHA Defence Phase 3,20.0,5.0,6.0,5445.0200,14508.670308,3.950000e+06

In [264]:
df5.shape

(10733, 8)

In [265]:
df5 = df5[df5["sqrt_ft"]/df5["beds"] > 250]

In [266]:
df5.shape

(10532, 8)