In [96]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [97]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1i0PiCCl9dXhxMDuR47a2TOQWrsa99m650wq_hHbawHY/export?format=csv")

In [98]:
df.shape

(14775, 9)

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14775 entries, 0 to 14774
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   listing_id  14740 non-null  float64
 1   title       14775 non-null  object
 2   price_text  14775 non-null  object
 3   price_pkr   14775 non-null  int64
 4   location    14775 non-null  object
 5   area_text   14775 non-null  object
 6   area_marla  14775 non-null  float64
 7   beds        13868 non-null  float64
 8   baths       13735 non-null  float64
dtypes: float64(4), int64(1), object(4)
memory usage: 1.0+ MB

In [100]:
df.isnull().sum()

listing_id      35
title            0
price_text       0
price_pkr        0
location         0
area_text        0
area_marla       0
beds           907
baths         1040
dtype: int64

In [101]:
df.describe()

         listing_id     price_pkr    area_marla          beds         baths
count  1.474000e+04  1.477500e+04  14775.000000  13868.000000  13735.000000
mean   5.410078e+07  9.304380e+07     15.953861      4.453057      4.555661
std    1.590959e+06  1.698869e+08     47.993253      1.983534      1.806038
min    1.745226e+07  8.000000e+04      0.900000      1.000000      1.000000
25%    5.411223e+07  2.500000e+07      5.000000      3.000000      3.000000
50%    5.460245e+07  4.450000e+07      8.000000      5.000000      5.000000
75%    5.477557e+07  9.250000e+07     14.400000      6.000000      6.000000
max    5.487768e+07  4.000000e+09   1760.000000     11.000000     10.000000

In [102]:
df.head()

,listing_id,title,price_text,price_pkr,location,area_text,area_marla,beds,baths
0,54844773.0,House At Prime Location,5.5 Crore,55000000,"D-12/1, D-12",4 Marla,4.0,3.0,5.0
1,54852451.0,Luxury 3-Bedroom Apartment For Sale In Warda H...,5.15 Crore,51500000,"Warda Hamna Residencia, G-11 Markaz",8.7 Marla,8.7,3.0,3.0
2,52696760.0,One kanal Beautiful luxurious FULL FURNISHED H...,10.9 Crore,109000000,"DHA Defence Phase 2, DHA Defence",1 Kanal,20.0,5.0,6.0
3,54793832.0,1 Kanal Luxury House Most Beautiful Prime Loca...,11.9 Crore,119000000,"DHA Defence Phase 2, DHA Defence",1 Kanal,20.0,6.0,6.0
4,54798682.0,Investor Price 1 Kanal Elegant House For Sale ...,7.9 Crore,79000000,"DHA Defence Phase 3, DHA Defence",1 Kanal,20.0,5.0,6.0

In [103]:
df.isnull().sum()

listing_id      35
title            0
price_text       0
price_pkr        0
location         0
area_text        0
area_marla       0
beds           907
baths         1040
dtype: int64

In [104]:
df1 = df.drop(columns=["listing_id", "title", "price_text", "area_text"])

In [105]:
df1.isnull().sum()

price_pkr        0
location         0
area_marla       0
beds           907
baths         1040
dtype: int64

In [106]:
df2 = df1.dropna()

In [107]:
df2

,price_pkr,location,area_marla,beds,baths
0,55000000,"D-12/1, D-12",4.0,3.0,5.0
1,51500000,"Warda Hamna Residencia, G-11 Markaz",8.7,3.0,3.0
2,109000000,"DHA Defence Phase 2, DHA Defence",20.0,5.0,6.0
3,119000000,"DHA Defence Phase 2, DHA Defence",20.0,6.0,6.0
4,79000000,"DHA Defence Phase 3, DHA Defence",20.0,5.0,6.0
...,...,...,...,...,...
14770,7500000,"Taramrri, Islamabad",4.0,3.0,2.0
14771,15500000,"Faisal Hills - Block A, Faisal Hills",5.0,3.0,4.0
14772,17000000,"PHAF Officers Residencia, Kuri Road",4.4,3.0,2.0
14773,82500000,"Margalla Town Phase 2, Margalla Town",8.0,7.0,6.0
14774,42000000,"G-11, Islamabad",4.4,5.0,5.0

In [108]:
df2.duplicated().sum()

np.int64(2763)

In [109]:
df3 = df2.drop_duplicates()

In [110]:
display(df3.shape)
display(df3.duplicated().sum())
display(df3.isnull().sum())

(10733, 5)

np.int64(0)

price_pkr     0
location      0
area_marla    0
beds          0
baths         0
dtype: int64

In [111]:
df3.head()

   price_pkr                             location  area_marla  beds  baths
0   55000000                         D-12/1, D-12         4.0   3.0    5.0
1   51500000  Warda Hamna Residencia, G-11 Markaz         8.7   3.0    3.0
2  109000000     DHA Defence Phase 2, DHA Defence        20.0   5.0    6.0
3  119000000     DHA Defence Phase 2, DHA Defence        20.0   6.0    6.0
4   79000000     DHA Defence Phase 3, DHA Defence        20.0   5.0    6.0

In [113]:
df3["sqrt_ft"] = df["area_marla"] * 272.251
df3.head()

/tmp/ipykernel_6280/1015283828.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3["sqrt_ft"] = df["area_marla"] * 272.251

,price_pkr,location,area_marla,beds,baths,sqrt_ft
0,55000000,"D-12/1, D-12",4.0,3.0,5.0,1089.0040
1,51500000,"Warda Hamna Residencia, G-11 Markaz",8.7,3.0,3.0,2368.5837
2,109000000,"DHA Defence Phase 2, DHA Defence",20.0,5.0,6.0,5445.0200
3,119000000,"DHA Defence Phase 2, DHA Defence",20.0,6.0,6.0,5445.0200
4,79000000,"DHA Defence Phase 3, DHA Defence",20.0,5.0,6.0,5445.0200

In [114]:
df3["price_per_sqrt_ft"] = df3["price_pkr"] / df3["sqrt_ft"]
df3["price_per_marla"] = df3["price_pkr"] / df3["area_marla"]

/tmp/ipykernel_6280/1498609760.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3["price_per_sqrt_ft"] = df3["price_pkr"] / df3["sqrt_ft"]
/tmp/ipykernel_6280/1498609760.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3["price_per_marla"] = df3["price_pkr"] / df3["area_marla"]

In [115]:
df3.head()

,price_pkr,location,area_marla,beds,baths,sqrt_ft,price_per_sqrt_ft,price_per_marla
0,55000000,"D-12/1, D-12",4.0,3.0,5.0,1089.0040,50504.864996,1.375000e+07
1,51500000,"Warda Hamna Residencia, G-11 Markaz",8.7,3.0,3.0,2368.5837,21742.951284,5.919540e+06
2,109000000,"DHA Defence Phase 2, DHA Defence",20.0,5.0,6.0,5445.0200,20018.291944,5.450000e+06
3,119000000,"DHA Defence Phase 2, DHA Defence",20.0,6.0,6.0,5445.0200,21854.832489,5.950000e+06
4,79000000,"DHA Defence Phase 3, DHA Defence",20.0,5.0,6.0,5445.0200,14508.670308,3.950000e+06

In [116]:
df4 = df3.copy()

In [128]:
def correctLocationNames(location):
  return location.strip().split(", ")[0].split("/")[0]

In [130]:
df4["location"] = df4["location"].apply(correctLocationNames)

In [117]:
df4["location"].unique()

array(['D-12/1, D-12', 'Warda Hamna Residencia, G-11 Markaz',
       'DHA Defence Phase 2, DHA Defence',
       'DHA Defence Phase 3, DHA Defence', 'G-13, Islamabad',
       'G-9/4, G-9', 'DHA Phase 5 - Sector F, DHA Defence Phase 5',
       'Jinnah Gardens Phase 1, Jinnah Gardens', 'D-12, Islamabad',
       'D-12/4, D-12', 'Smama Star Mall & Residency, Gulberg Greens',
       'Faisal Town Phase 1 - Block A, Faisal Town Phase 1',
       'Diplomatic Enclave, Islamabad', 'J7 Emporium, B-17',
       'Skypark One, Gulberg Greens', 'D-17, Islamabad',
       'Oleander Sector - DHA Homes Block A, DHA Valley - Oleander Sector',
       'Top City 1, Islamabad', 'I-11, Islamabad', 'F-10, Islamabad',
       'Bahria Enclave - Sector B1, Bahria Enclave',
       'Goldcrest Highlife, DHA Defence Phase 2', 'F-6/3, F-6',
       'Bahria Enclave - Sector A, Bahria Enclave',
       'Bahria Enclave - Sector C1, Bahria Enclave',
       'Jinnah Gardens, FECHS', 'G-15, Islamabad', 'G-13/1, G-13',
       'Bahria Enclave, Bahria Town', 'Top City 1 - Block B, Top City 1',
       'Top City 1 - Block A, Top City 1', 'Mumtaz City, Islamabad',
       'Soan Garden - Block G, Soan Garden', 'B-17, Islamabad',
       'G-14/4, G-14', 'Gulberg, Islamabad',
       'Margalla Valley - C-12, Islamabad',
       'Ministry of Commerce Society, E-19', 'F-7, Islamabad',
       'I-10/2, I-10', 'Karakoram Diplomatic Enclave, Islamabad',
       'Bani Gala, Islamabad', 'Faisal Margalla City, B-17',
       'G-15 Markaz, G-15', 'G-11/3, G-11', 'G-13/4, G-13',
       'G-10/3, G-10', 'E-11/3, E-11', 'F-6, Islamabad',
       'MPCHS - Multi Gardens, B-17', 'The Centaurus, F-8',
       'F-11/1, F-11', 'F-11, Islamabad',
       'DHA Phase 2 - Sector A, DHA Defence Phase 2',
       'MPCHS - Block E, MPCHS - Multi Gardens',
       'Faisal Hills - Executive Block, Faisal Hills', 'G-13/2, G-13',
       'E-7, Islamabad', 'The Galleria, Bahria Enclave', 'I-8, Islamabad',
       'Defence Residency, DHA Defence Phase 2',
       'DHA Defence Phase 5, DHA Defence',
       'DHA Phase 2 - Sector B, DHA Defence Phase 2',
       'DHA Phase 2 - Sector D, DHA Defence Phase 2',
       'Bahria Enclave - Sector J, Bahria Enclave',
       'Bahria Enclave - Sector C, Bahria Enclave',
       'Silver Oaks Apartments, F-10', 'I-8/4, I-8',
       'MPCHS - Block F, MPCHS - Multi Gardens',
       'Zaraj Housing Scheme, Islamabad',
       'Margalla View Society - Block D, Margalla View Housing Society',
       'Bahria Enclave - Sector H, Bahria Enclave',
       'Bahria Enclave - Sector N, Bahria Enclave', 'I-10/4, I-10',
       'G-8, Islamabad', 'Regent One, DHA Defence Phase 3',
       'G-10/1, G-10', 'Faisal Hills, Islamabad',
       'Sukh Chayn Residence, F-10', 'I-11/2, I-11',
       'Mumtaz City - Chanab Block, Mumtaz City', 'G-10, Islamabad',
       'C-18, Islamabad', 'I-14, Islamabad',
       'MPCHS - Block A, MPCHS - Multi Gardens', 'G-10/4, G-10',
       'MPCHS - Block C, MPCHS - Multi Gardens',
       'Gandhara City, Islamabad', 'F-11 Markaz, F-11',
       'Chak Shahzad Farms, Chak Shahzad', 'F-11/2, F-11',
       'F-8, Islamabad', 'Naval Anchorage - Block J, Naval Anchorage',
       'G-16/4, G-16', 'Eighteen, Kashmir Highway', 'E-11, Islamabad',
       'F-17, Islamabad', 'MPCHS - Block C1, MPCHS - Multi Gardens',
       'Faisal Hills - Block A, Faisal Hills',
       'Samama Gulberg Tower, Gulberg Greens - Block B',
       'Royal Homes, Lehtrar Road', 'G-14, Islamabad',
       'Lehtrar Road, Islamabad', 'Gulberg Greens, Gulberg', 'I-8/2, I-8',
       'I-14/3, I-14', 'Gulberg Residencia - Block F, Gulberg Residencia',
       'I-14/4, I-14', 'Ghauri Town, Islamabad',
       'Karakoram Greens, Gulberg Greens', 'E-18, Islamabad',
       'Top City 1 - Block D, Top City 1',
       'Park View City - Downtown Block, Park View City',
       'Ghauri Town Phase 4 C2, Ghauri Town',
       'Askari Heights 5, DHA Defence Phase 5', 'Soan Garden, Islamabad',
       'I-10/1, I-10', 'I-9, Islamabad', 'Madina Tower, E-11',
       'DHA Valley, DHA Defence', 'I-8/3, I-8', 'I-14/1, I-14',
       'Soan Garden - Block A, Soan Garden',
       'Gulberg Residencia, Gulberg', 'Capital Resorts, E-11/4',
       'DHA Phase 3 - Block B, DHA Defence Phase 3',
       'Bahria Enclave - Sector I, Bahria Enclave', 'The Arch, G-11/3',
       'Faisal Town Phase 1, Faisal Town - F-18',
       'Islamabad Expressway, Islamabad', 'Apollo Towers, E-11/4',
       'DHA Phase 2 - Sector F, DHA Defence Phase 2',
       'Park View City - Overseas Block, Park View City', 'G-15/1, G-15',
       'Gulberg Residencia - Block C, Gulberg Residencia',
       'DHA Defence Phase 1, DHA Defence',
       'Gulberg Residencia - Block T, Gulberg Residencia',
       'Gulberg Greens - Block C, Gulberg Greens',
       'Naval Anchorage - Block F, Naval Anchorage',
       'Park View City, Islamabad', 'Executive Heights, F-11',
       'Mumtaz City - Indus Block, Mumtaz City', 'F-10/3, F-10',
       'H-13, Islamabad', 'Nazim-ud-din Road, Islamabad',
       'Park Avenue, F-11', '11 Central Apartments, G-11/1',
       'MPCHS - Block B, MPCHS - Multi Gardens',
       'Bahria Garden City, Bahria Town',
       'Bahria Enclave - Sector G, Bahria Enclave', 'F-11/4, F-11',
       'Korang Town, Islamabad', 'F-8/4, F-8', 'G-9/3, G-9', 'F-8/1, F-8',
       'G-9/1, G-9', 'Askari Heights 4, DHA Phase 5 - Sector H',
       'Cube Apartments, Bahria Enclave', 'F-10/1, F-10',
       'Goldcrest Views, DHA Defence Phase 2',
       'DHA Phase 2 - Sector G, DHA Defence Phase 2',
       'Zeta-1 Mall, GT Road', 'F-8/3, F-8',
       'Askari Tower 3, DHA Defence Phase 5',
       'Five Star Residence, G-11/3',
       'Gulberg Residencia - Block I, Gulberg Residencia',
       'Askari Tower 1, DHA Defence Phase 2',
       'DHA Phase 5 - Sector A, DHA Defence Phase 5',
       'Park View - Block H, Park View City',
       'PWD Housing Society - Block C, PWD Housing Scheme',
       'The Veranda Residence, E-11/1', 'G-11, Islamabad',
       'Bahria Enclave - Sector M, Bahria Enclave',
       'New Blue Area, Islamabad', 'Capital Residencia, Margalla Hills-2',
       'MPCHS - Block D, MPCHS - Multi Gardens', 'G-6, Islamabad',
       'DHA Valley - Oleander Sector, DHA Valley',
       'Faisal Town - F-18, Islamabad', 'D-12/2, D-12',
       'Zarkon Heights, G-15',
       'Gulshan-e-Sehat 1 - Block A, Gulshan-e-Sehat 1',
       'National Police Foundation O-9, Islamabad',
       'National Police Foundation O-9 - Block C, National Police Foundation O-9',
       'Ivory, Bahria Town', 'Lignum Tower, DHA Defence Phase 2',
       'Gulberg Arena Mall, Gulberg Greens', 'F-7/1, F-7',
       'Bahria Enclave - Sector F, Bahria Enclave',
       'Bahria Enclave - Sector F1, Bahria Enclave', 'Tarlai, Islamabad',
       'Gulberg Greens - Block B, Gulberg Greens', 'G-9, Islamabad',
       'F-10/4, F-10', 'DHA Homes, DHA Valley', 'F-10/2, F-10',
       'Naval Anchorage - Block M, Naval Anchorage',
       'Airport Green Garden - Block B, Airport Green Garden',
       'The Royal Mall and Residency, Bahria Enclave',
       'Emaar Canyon Views, Islamabad',
       'Bahria Enclave - Sector C2, Bahria Enclave',
       'Pakistan Town - Phase 2, Pakistan Town', 'D-12/3, D-12',
       'G-14/2, G-14', 'Park View - Block B, Park View City',
       'Mall of Imarat, Jinnah Gardens',
       'Fazaia Housing Scheme Block F, Fazaia Housing Scheme',
       'E-11/4, E-11', 'River Garden, Islamabad', 'G-14/3, G-14',
       'Prince Road, Bhara kahu',
       'Gulberg Residencia - Block E, Gulberg Residencia',
       'Ghauri Town Phase 5B, Ghauri Town',
       'Ghauri Town Phase 5A, Ghauri Town', 'G-7/4, G-7', 'F-11/3, F-11',
       'Margalla View Housing Society, D-17',
       'The Gate Mall & Apartments, Faisal Town - F-18',
       'Fazaia Housing Scheme Block D, Fazaia Housing Scheme',
       'DHA Phase 2 - Sector C, DHA Defence Phase 2',
       'PHAF Officers Residencia, Kuri Road',
       'Park View - Block F, Park View City', 'F-6/1, F-6',
       'G-15/2, G-15', 'I-10, Islamabad',
       'Ghauri Town Phase 5, Ghauri Town', 'Gulberg Town, Lehtrar Road',
       'The Fourth Star Residence, G-11/3',
       'Giga Mall Extension Tower, DHA Defence Phase 2',
       'CBR Town Phase 1 - Block C, CBR Town Phase 1',
       'Naval Anchorage, Islamabad', 'Warda Hamna Residencia 3, G-11/3',
       'Capital Heights, G-11/3', 'G-8/1, G-8',
       'Al-Safa Heights, F-11 Markaz', '18 West Residencia, F-11/1',
       'Defence Executive Apartments, DHA Defence Phase 2',
       'El Cielo, GT Road', 'Gulberg Heights, Gulberg Greens',
       'Federation Housing Society - O-9, National Police Foundation O-9',
       'Capital Square, B-17',
       'DHA Phase 5 - Sector D, DHA Defence Phase 5',
       'CBR Town Phase 1 - Block D, CBR Town Phase 1',
       'Green Avenue, Islamabad', 'I-14/2, I-14',
       'DHA Phase 1 - Sector F, DHA Defence Phase 1',
       'DHA Phase 5 - Sector B, DHA Defence Phase 5',
       'Naval Anchorage - Block E, Naval Anchorage',
       'Ghauri Town Phase 4A, Ghauri Town', 'G-8/2, G-8', 'F-7/2, F-7',
       'Regent One - Tower B, DHA Defence Phase 3',
       'Deans Apartments, G-11/3',
       'Naval Anchorage - Block L, Naval Anchorage',
       'Faisal Hills - Block B, Faisal Hills',
       'CBR Town Phase 1, CBR Town', 'Gulberg Icon 2, Gulberg Greens',
       'G-15/4, G-15', 'Soan Garden - Block E, Soan Garden',
       'Naval Anchorage - Block C, Naval Anchorage',
       'Gulberg Greens - Block E, Gulberg Greens',
       'Gulshan-e-Sehat 2 - Block F, Gulshan-e-Sehat 2', 'F-7/4, F-7',
       'I-16, Islamabad', 'G-15/3, G-15', 'Chak Shahzad, Islamabad',
       'Gulberg Residencia - Block L, Gulberg Residencia',
       'Bahria Enclave - Sector C3, Bahria Enclave', 'G-13/3, G-13',
       'Rawal Enclave - Phase 1, Rawal Enclave',
       'Gulberg Greens - Executive Block, Gulberg Greens',
       'The Atrium, Zaraj Housing Scheme', 'G-8/3, G-8',
       'Gulberg Greens - Block A, Gulberg Greens', 'I-16/3, I-16',
       'Gulshan-e-Sehat 1, E-18',
       'Gulshan-e-Sehat 1 - Block D, Gulshan-e-Sehat 1',
       'GT Road, Islamabad', 'I-15/1, I-15',
       'Pine Heights Luxury Apartments, D-17',
       'Oleander Sector - Block B, DHA Valley - Oleander Sector',
       'Oleander Sector - DHA Homes, DHA Valley - Oleander Sector',
       'G-6/3, G-6', 'Gulberg Greens - Block D, Gulberg Greens',
       'DHA Phase 5 - Sector C, DHA Defence Phase 5',
       'DHA Phase 5 - Sector J, DHA Defence Phase 5',
       'Gulberg Residencia - Block O, Gulberg Residencia',
       'Hyde Park One, Canyon Views Cvrp',
       'Margalla Town Phase 1, Margalla Town',
       'Park View City - Townhouses, Park View - Block J',
       'Faisal Town Phase 1 - Block C, Faisal Town Phase 1',
       'Koral Town, Islamabad', 'Ghauri Garden, Ghauri Town',
       'DHA Phase 1 - Defence Villas, DHA Phase 1 - Sector F',
       'Telegardens (T&T ECHS), F-17',
       'City Mall & Residences, Top City 1',
       'Top City 1 - Block C, Top City 1',
       'Airport Green Garden - Block A, Airport Green Garden',
       'Park View - Block J, Park View City',
       'Lilly Sector - DHA Homes, DHA Valley - Lilly Sector',
       'Shehzad Town, Islamabad',
       'Pakistan Housing Authority Apartments, I-12/1',
       'Soan Garden - Block H, Soan Garden',
       'DHA Phase 1 - Sector E, DHA Defence Phase 1',
       'Airport Enclave E, Airport Enclave',
       'Askari Tower 2, DHA Defence Phase 2', 'G-10/2, G-10',
       'Airport Enclave A, Airport Enclave',
       'Gulberg Residencia - Block V, Gulberg Residencia',
       'Soan Garden - Block D, Soan Garden', 'Shams Colony, H-13',
       'Bhatti Town, Gulberg Expressway', 'Bilal Town, Lehtrar Road',
       'Spring Valley, Islamabad', 'Soan Garden - Block B, Soan Garden',
       'PWD Housing Scheme, Islamabad', 'CBR Town, Islamabad',
       'Madina Town, Islamabad', 'Garden Town, Islamabad', 'G-9/2, G-9',
       'Gulshan-e-Sehat 2 - Block G, Gulshan-e-Sehat 2', 'E-16/3, E-16',
       'G-16/3, G-16', 'E-11/2, E-11',
       'Faisal Town Phase 1 - Block B, Faisal Town Phase 1',
       'Top City 1 - Block J, Top City 1',
       'Gulberg Residencia - Block J, Gulberg Residencia',
       'Naval Farms Housing Scheme, Islamabad',
       'Diamond Mall & Residency, Gulberg Greens',
       'Al-Ghurair Giga - Block 14, Al-Ghurair Giga', 'I-12/1, I-12',
       'F-17/2, F-17',
       'Luxus Mall and Residency, Gulberg Greens - Block B',
       'Pakistan Town - Phase 1, Pakistan Town', 'PECHS - Block K, PECHS',
       'Gulberg Residencia - Block H, Gulberg Residencia',
       'Emaar Canyon Views - Alma 1 Block, Emaar Canyon Views',
       'DHA Defence Phase 4, DHA Defence', 'Thanda Pani, Islamabad',
       'Al-Ghurair Giga, DHA Defence Phase 2', 'Kuri Road, Islamabad',
       'DHA Phase 4 - Sector A, DHA Defence Phase 4',
       'Margalla Orchard, Islamabad',
       'Gulberg Residencia - Block A, Gulberg Residencia',
       'Akbar Vista, 1st Avenue', 'Veranda Executive, G-10 Markaz',
       'Koral Chowk, Islamabad',
       'University Town - Block A, University Town',
       'Naval Anchorage - Block K, Naval Anchorage',
       'DHA Phase 2 - Sector J, DHA Defence Phase 2',
       'Mall of Islamabad, Blue Area', 'Fazaia Housing Scheme, Tarnol',
       'National Police Foundation O-9 - Block F, National Police Foundation O-9',
       'Gulberg Business Square, Gulberg', 'G-7/2, G-7',
       'Al-Ghurair Giga - Block 17, Al-Ghurair Giga',
       'MPCHS - Block B Extension 1, MPCHS - Multi Gardens',
       'Multi Residencia & Orchards, Islamabad',
       'Ghauri Town Phase 3, Ghauri Town',
       'Cabinet Division Employees Cooperative Housing Society, E-17',
       'Bahria Garden City - Zone 1, Bahria Garden City',
       'National Police Foundation O-9 - Block B, National Police Foundation O-9',
       'Askari Heights, DHA Defence Phase 4',
       'DHA Phase 2 - Sector E, DHA Defence Phase 2', 'I-12, Islamabad',
       'I-9/4, I-9', 'Askari Tower 4, DHA Defence Phase 5',
       'Ghauri Town Phase 7, Ghauri Town', 'G-11/2, G-11',
       'Islamabad Heights, G-15/4', 'I-8/1, I-8',
       'Chatha Bakhtawar, Islamabad', 'Marwa Town - Block C, Marwa Town',
       'F-10 Markaz, F-10', 'The Residences, Faisal Hills',
       'Soan Garden - Block F, Soan Garden',
       'Margalla View Society - Block C, Margalla View Housing Society',
       'DHA Phase 1 - Sector B, DHA Defence Phase 1',
       'Faisal Hills - Block C, Faisal Hills',
       'Canary Residency, Faisal Hills', 'Park One, F-10/3', 'F-6/2, F-6',
       'Top City 1 - Kanwar Moiz Block, Top City 1',
       'Radisson BLU Hotel & Residences, Mumtaz City',
       'Gulshan-e-Sehat 2 - Block E, Gulshan-e-Sehat 2',
       'Al-Ghurair Giga - Block 12, Al-Ghurair Giga',
       'Green Heights, MPCHS - Block A', 'G-11/4, G-11',
       'PECHS, Islamabad', 'Naval Anchorage - Phase 1, Naval Anchorage',
       'Minara Residence, GT Road', 'Park Road, Islamabad',
       'DHA Valley - Lilly Sector, DHA Valley', 'Makkah Tower, E-11',
       'Hussain Abad, Islamabad', 'Nilore, Islamabad',
       'Model Town Humak, Islamabad', 'F-17/3, F-17', 'G-11/1, G-11',
       'Fazaia Housing Scheme Block A, Fazaia Housing Scheme',
       'Gulberg Business Park, Gulberg', 'F-7/3, F-7',
       'DHA Phase 3 - Block A, DHA Defence Phase 3',
       'Park Enclave 1, Park Enclave',
       'PWD Housing Society - Block B, PWD Housing Scheme',
       'Lilly Sector - Block B, DHA Valley - Lilly Sector',
       'Paradise Villa Apartments, D-17',
       'Askari Tower 5, DHA Defence Phase 5', 'Pakistan Town, Islamabad',
       'Orchard Scheme, Islamabad', 'Karakoram Enclave 1, Islamabad',
       'Al-Ghurair Giga - Block 11, Al-Ghurair Giga',
       'Bhara kahu, Islamabad', 'Khudadad Heights, E-11/2',
       'Country Club Apartments, Islamabad - Murree Expressway',
       'Bahria Golf City, Bahria Town',
       'Park View - Block A, Park View City',
       'Park View - Block E, Park View City', 'E-11/1, E-11',
       'Rawat, Islamabad', 'Karakoram Enclave 2, F-11', 'E-17/3, E-17',
       'F-15, Islamabad', 'Raja Akhtar Road, Islamabad', 'G-6/1, G-6',
       'CDECHS - Cabinet Division Employees Cooperative Housing Society, E-16/3',
       'Ghauri Town Phase 4B, Ghauri Town',
       'Margalla Town Phase 2, Margalla Town',
       'Pine City Housing Society, Pir Sohawa Road',
       'Zamar Valley, Kashmir Highway',
       'Akbar Arcade, Gulberg Greens - Block C', 'I-16/4, I-16',
       'Al-Ghurair Giga - Block 16, Al-Ghurair Giga',
       'DHA Phase 1 - Sector C, DHA Defence Phase 1',
       'DHA Phase 5 - Sector F1, DHA Defence Phase 5',
       'DHA Phase 2 - Sector H, DHA Defence Phase 2',
       'AJ Towers, Gulberg Greens - Block A',
       'Mumtaz City - Ravi Block, Mumtaz City',
       'Kazani Heights, Islamabad Expressway',
       'Engineering Co-operative Housing (ECHS), Islamabad',
       'Tarnol, Islamabad',
       'PWD Housing Society - Block D, PWD Housing Scheme',
       'PWD Housing Society - Block A, PWD Housing Scheme',
       'Marwa Town, Islamabad', 'G-6/2, G-6', 'Rawal Town, Islamabad',
       'Aabpara Market, G-6/1',
       'DHA Phase 5 - Sector K, DHA Defence Phase 5',
       'Al-Ghurair Giga - Block 5, Al-Ghurair Giga',
       'Islamabad - Murree Expressway, Islamabad',
       'The Palazzo, Gulberg Greens - Block A',
       'Airport Green Garden, Kashmir Highway', 'I-11/1, I-11',
       'G-11 Markaz, G-11', 'Japan Road, Islamabad',
       'Park Enclave, Islamabad', 'Swan Garden, Islamabad',
       'AGOCHS Phase 1, AGOCHS', 'Kiyani Town Phase 1, Kiyani Town',
       'Lilly Sector - Block E, DHA Valley - Lilly Sector',
       'D Mall, DHA Defence Phase 2',
       'Faisal Hills - Prime Block, Faisal Hills',
       'Bahria Town, Islamabad', 'Sihala, Islamabad',
       'Naval Anchorage - Block G, Naval Anchorage',
       'Margalla Hills-2, E-11', 'Rania Heights, Zaraj Housing Scheme',
       'Ministry of Commerce Society - Block B, Ministry of Commerce Society',
       'Pir Sohawa Road, Pir Sohawa', 'Garden Residence, F-10/4',
       'Nova City, Islamabad',
       'University Town - Block C, University Town', 'I-9/1, I-9',
       'Zaraj Scheme - Sector C, Zaraj Housing Scheme',
       'Taramrri, Islamabad', 'I-16 Markaz, I-16',
       'Khanna East, Islamabad',
       'Multi Residencia & Orchards - Block C, Multi Residencia & Orchards',
       'Murree Road, Islamabad',
       'Al-Ghurair Giga - Block 7, Al-Ghurair Giga',
       'Marwa Town - Block B, Marwa Town', 'Elysium Mall, Blue Area',
       'Axis Mall & Apartments, Islamabad',
       'Eden Life Islamabad, Islamabad', 'Ovais Co Heights, PWD Road',
       'AGOCHS, Islamabad', 'DHA Phase 5 - Sector H, DHA Defence Phase 5',
       'Rahman Enclave, Lehtrar Road', 'Islamabad Highway, Islamabad',
       'Azmat Town, Islamabad', 'G-16, Islamabad', 'Blue Area, Islamabad',
       'Engineers Co-operative Housing, D-18', 'F-7 Markaz, F-7',
       'Florence Galleria, DHA Phase 2 - Sector C', 'D-18, Islamabad',
       'National Police Foundation O-9 - Block A, National Police Foundation O-9',
       'Shaheen Town Phase 2, Shaheen Town',
       'DHA Defence Phase 7, DHA Defence',
       'Marwa Town - Block A, Marwa Town', 'D-12 Markaz, D-12',
       'Margalla View Society - Block A, Margalla View Housing Society',
       'Royal Avenue, Islamabad', 'F-8/2, F-8',
       'Shah Allah Ditta, Islamabad',
       'Elanza Mall & Residency, Gulberg Residencia - Block D',
       'Airport Enclave, Islamabad', 'E-17, Islamabad',
       'Naval Anchorage - Block D, Naval Anchorage', 'F-15/1, F-15',
       'DHA Phase 1 - Sector A, DHA Defence Phase 1',
       'Airport Avenue Housing Society, Islamabad',
       'Margalla Gateway Tower, E-11/4', 'G-13 Markaz, G-13',
       'NORA Residences, GT Road', 'Margalla Town, Islamabad',
       'Sohan Valley, Islamabad',
       'DHA Phase 1 - Sector D, DHA Defence Phase 1',
       'Khudadad Heights, E-11/4', 'Ali Pur, Islamabad',